name: peft-tutorial
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - torch
      - transformers
      - datasets
      - accelerate
      - scikit-learn
      - peft
